apriltag_node:                 # node name
  ros__parameters:
    # setup (defaults)
    image_transport: raw  # image format: "raw" or "compressed"
    family: 36h11         # tag family name: 16h5, 25h9, 36h11
    size: 0.08             # default tag edge size in meter
    profile: false        # print profiling information to stdout

    # tuning of detection (defaults)
    # (optional) list of tags
    # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
    tag:
      ids:    [0, 1, 2]         # tag IDs for which to publish transform
      frames: [base_tag, board, mole]   # frame names
      sizes:  [0.08, 0.08, 0.08]  # tag-specific edge size, overrides the default 'size'
      # Optional sizes:  [<size1>, <size1>     # tag-specific edge size, overrides the default 'size'